modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = '''
${description}
'''
logoFile = "${mod_icon}"

[[dependencies.sound_gc]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sound_gc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sound_gc]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.68,)"
ordering = "AFTER"
side = "BOTH"
