plugins {
    id 'io.github.crimix.replace-placeholders' version '3.0'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

replaceResourcePlaceholders {
    enabled true
    filesToExpand 'fabric.mod.json'
    extraProperties 'version', 'mod_id'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
