plugins {
    id ("dev.architectury.loom") version "1.13.467" apply false
    id ("architectury-plugin") version "3.4.162"
    id ("com.gradleup.shadow") version "8.3.6"
    id ("soundgc.convention") apply false
}


allprojects {
    apply(plugin: "architectury-plugin")
    group = rootProject.maven_group
    version = rootProject.mod_version
    architectury {
        minecraft = rootProject.minecraft_version
        compileOnly()
    }
}

subprojects {
    apply(plugin: "soundgc.convention")
}
