# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = org.fury_phoenix.soundgc
mod_id = soundgc
enabled_platforms = forge
placeholder.author = Fury_Phoenix
placeholder.name = SoundGC
placeholder.description = Garbage collects sounds!
placeholder.license = ARR
placeholder.mod_icon = icon.png

# Minecraft properties
minecraft_version = 1.17.1

# Dependencies
fabric_loader_version = 0.18.4
fabric_api_version = 0.42.0+1.16
forge_version = 1.17.1-37.1.1
