# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = org.fury_phoenix.soundgc
mod_id = soundgc
enabled_platforms = fabric,forge
placeholder.author = Fury_Phoenix
placeholder.name = Sound GC
placeholder.description = Garbage collects sounds!
placeholder.license = ARR
placeholder.mod_icon = assets/sound_gc/icon.png

# Minecraft properties
minecraft_version = 1.16.5

# Dependencies
architectury_api_version = 1.32.68
fabric_loader_version = 0.18.4
fabric_api_version = 0.42.0+1.16
forge_version = 1.16.5-36.2.42
