plugins {
    id 'io.github.crimix.replace-placeholders' version '3.0'
}

loom {
    forge {
        mixinConfig "sound_gc.mixins.json"
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
}

replaceResourcePlaceholders {
    enabled true
    filesToExpand 'META-INF/mods.toml'
    extraProperties 'version', 'mod_id'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
